syntax = "proto3";

package example13.service_a;

option go_package = "example13/service_a_pb";


message RequestA {
    string input_data = 1;
    bool trigger_broker_call_to_external = 2;
    bool trigger_internal_call_to_b = 3;
}

message ResponseA {
    string processed_data_A = 1;
    string data_from_B = 2;
    string data_from_external = 3;
}

// ServiceA: Entry point for client requests, orchestrates calls to ServiceB and ExternalService (via broker)
service ServiceA {
    rpc ProcessDataA(RequestA) returns (ResponseA);
}
