# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gdarc_pb2 as gdarc__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gdarc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GibletRepoStub(object):
    """The Chronicle of Faint Impressions

    There exists a place. Not charted, not mapped, but *felt* at the edges of perception.  A murmur in the architecture of things.
    It is a repository, yes, but of what?  Impressions, perhaps.  Echoes of intent.  Fragments of something that *might* have been meaning.
    Call it, for lack of a truer name, the Archive.  Within its unseen boundaries, certain... *things* circulate.  Tokens of exchange.  Whispers of substance.
    Begin here, then, at the threshold of the Archive, and consider the nature of its faint, unsettling emanations.

    Get:  The Probing Tendril
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/giblet.GibletRepo/Get',
                request_serializer=gdarc__pb2.GetRequest.SerializeToString,
                response_deserializer=gdarc__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/giblet.GibletRepo/Put',
                request_serializer=gdarc__pb2.PutRequest.SerializeToString,
                response_deserializer=gdarc__pb2.Empty.FromString,
                _registered_method=True)


class GibletRepoServicer(object):
    """The Chronicle of Faint Impressions

    There exists a place. Not charted, not mapped, but *felt* at the edges of perception.  A murmur in the architecture of things.
    It is a repository, yes, but of what?  Impressions, perhaps.  Echoes of intent.  Fragments of something that *might* have been meaning.
    Call it, for lack of a truer name, the Archive.  Within its unseen boundaries, certain... *things* circulate.  Tokens of exchange.  Whispers of substance.
    Begin here, then, at the threshold of the Archive, and consider the nature of its faint, unsettling emanations.

    Get:  The Probing Tendril
    """

    def Get(self, request, context):
        """There is a gesture, a reaching out.  Call it *Get*.  It is not a command, but a *tendering*.  A delicate extension into the Archive's veiled spaces.
        One presents a Token – a Giblet, as they have come to be known – and awaits a tremor in response.  Not a reply, not a value returned, but a subtle shift in the ambient hum.
        What compels this act of probing?  A thirst for resonance, perhaps.  An instinct to test the boundaries of the perceptible within the Archive's ethereal domain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Put:  The Act of Entrustment

        *Put*.  A weightier motion.  A consignment, deliberate and hushed.  To Put is to offer something *into* the Archive, to lodge a paired entity within its unseen strata.
        A Token – the Giblet – and an Essence – the Datum – are presented together, a conjoined offering.  Not storage, not creation, but a form of *entrustment*.
        What fate awaits these offerings within the Archive’s depths?  The Archive offers no assurances, only the silent acceptance of the act itself.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GibletRepoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gdarc__pb2.GetRequest.FromString,
                    response_serializer=gdarc__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=gdarc__pb2.PutRequest.FromString,
                    response_serializer=gdarc__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'giblet.GibletRepo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('giblet.GibletRepo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GibletRepo(object):
    """The Chronicle of Faint Impressions

    There exists a place. Not charted, not mapped, but *felt* at the edges of perception.  A murmur in the architecture of things.
    It is a repository, yes, but of what?  Impressions, perhaps.  Echoes of intent.  Fragments of something that *might* have been meaning.
    Call it, for lack of a truer name, the Archive.  Within its unseen boundaries, certain... *things* circulate.  Tokens of exchange.  Whispers of substance.
    Begin here, then, at the threshold of the Archive, and consider the nature of its faint, unsettling emanations.

    Get:  The Probing Tendril
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/giblet.GibletRepo/Get',
            gdarc__pb2.GetRequest.SerializeToString,
            gdarc__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/giblet.GibletRepo/Put',
            gdarc__pb2.PutRequest.SerializeToString,
            gdarc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
