# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdarc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'gdarc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgdarc.proto\x12\x06giblet\"\x1c\n\nGetRequest\x12\x0e\n\x06giblet\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05\x64\x61tum\x18\x01 \x01(\x0c\"+\n\nPutRequest\x12\x0e\n\x06giblet\x18\x01 \x01(\t\x12\r\n\x05\x64\x61tum\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2f\n\nGibletRepo\x12.\n\x03Get\x12\x12.giblet.GetRequest\x1a\x13.giblet.GetResponse\x12(\n\x03Put\x12\x12.giblet.PutRequest\x1a\r.giblet.EmptyB=Z;github.com/provide-io/pyvider-rpcplugin/examples/grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdarc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/provide-io/pyvider-rpcplugin/examples/grpc/proto'
  _globals['_GETREQUEST']._serialized_start=23
  _globals['_GETREQUEST']._serialized_end=51
  _globals['_GETRESPONSE']._serialized_start=53
  _globals['_GETRESPONSE']._serialized_end=81
  _globals['_PUTREQUEST']._serialized_start=83
  _globals['_PUTREQUEST']._serialized_end=126
  _globals['_EMPTY']._serialized_start=128
  _globals['_EMPTY']._serialized_end=135
  _globals['_GIBLETREPO']._serialized_start=137
  _globals['_GIBLETREPO']._serialized_end=239
# @@protoc_insertion_point(module_scope)
