#!/bin/sh

export PLUGIN_SERVER_PATH=$(pwd)/bin/kv-go-server

export PLUGIN_PROTOCOL_VERSIONS=1
export PLUGIN_TRANSPORTS=unix
export PLUGIN_AUTO_MTLS=true

export PLUGIN_MAGIC_COOKIE_KEY=BASIC_PLUGIN
export PLUGIN_MAGIC_COOKIE=hello
export BASIC_PLUGIN=hello

# export PLUGIN_CLIENT_CERT="-----BEGIN CERTIFICATE-----
# MIICUDCCAbGgAwIBAgIRAIXx4LN4R0pJHtcBm+dDy24wCgYIKoZIzj0EAwQwKDES
# MBAGA1UECgwJSGFzaGlDb3JwMRIwEAYDVQQDDAlsb2NhbGhvc3QwIBcNMjUwMTIx
# MDE0OTM0WhgPMjA1NTAxMjExMjUwMDRaMCgxEjAQBgNVBAoMCUhhc2hpQ29ycDES
# MBAGA1UEAwwJbG9jYWxob3N0MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQB4gRa
# AIIWs8KSx2qJXCzTwlIoxZp6OmvnkkIn/dWXor01nUi5tiwMHmu/ub6j37hvU1jr
# Rq7y1hGY0eVDF5Ol+B0BANXzXd3XwnGsG2T68Qba4NkLfZSpJrujxiK5/z8Aa9CZ
# WOMj7tKNnXoxEY4C6VqIwe3rzThM0Xyj4JEyDWJKDdujdzB1MA8GA1UdEwEB/wQF
# MAMBAf8wFAYDVR0RBA0wC4IJbG9jYWxob3N0MB0GA1UdJQQWMBQGCCsGAQUFBwMC
# BggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAqwwHQYDVR0OBBYEFKYCLugDHq1NbRzE
# Jv/ANlLMOSxoMAoGCCqGSM49BAMEA4GMADCBiAJCAQ2x7O2hJVCVAFfmWMaFOfei
# 1Jn8nRtMzpuh4ERlDpwhaG9JCfWnC2mGf5FGyAi0BA0OA5+F+DYhlXRGh5zrnwk0
# AkIBaKMpFQXbczs7AhCXZ4uLzbvst/Ip5+e0JvM85KvoWKVEJMyGe+Cs321YVBhK
# KyLnECrFe5RwFvByno+38ULugJQ=
# -----END CERTIFICATE-----"
#
# export PLUGIN_CLIENT_KEY="-----BEGIN EC PRIVATE KEY-----
# MIHcAgEBBEIBEXjW2MmRmNOaqNoRiQGc7Zt8Fq+/zxX8s7GYGus/pz6eOIKeq1Ko
# whKXKbX7pnFwftzzfkuHr8+x87ZA3q/LBJ+gBwYFK4EEACOhgYkDgYYABAHiBFoA
# ghazwpLHaolcLNPCUijFmno6a+eSQif91ZeivTWdSLm2LAwea7+5vqPfuG9TWOtG
# rvLWEZjR5UMXk6X4HQEA1fNd3dfCcawbZPrxBtrg2Qt9lKkmu6PGIrn/PwBr0JlY
# 4yPu0o2dejERjgLpWojB7evNOEzRfKPgkTINYkoN2w==
# -----END EC PRIVATE KEY-----"

# export PLUGIN_SERVER_CERT="${PLUGIN_CLIENT_CERT}"
# export PLUGIN_SERVER_KEY="${PLUGIN_CLIENT_KEY}"

# This is a static certificate to use for testing.
# export PLUGIN_SERVER_CERT="-----BEGIN CERTIFICATE-----
# MIICUDCCAbGgAwIBAgIRAMidRxowAOTuODTStEBix08wCgYIKoZIzj0EAwQwKDES
# MBAGA1UECgwJSGFzaGlDb3JwMRIwEAYDVQQDDAlsb2NhbGhvc3QwIBcNMjUwMTIy
# MTg1NzA2WhgPMjA1NTAxMjIxMjU3MzZaMCgxEjAQBgNVBAoMCUhhc2hpQ29ycDES
# MBAGA1UEAwwJbG9jYWxob3N0MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBL5Tt
# eMzHc/5ftI6ifiEWLEE5j9gA7qLQIuyBqA8DDnOgwLKhrI8EfYh+QsUxf4cglzX4
# xLsaXX9ryEjPExeI1tQAjkUBCPGF4pJQRtbYnVFi6y0OeQfSqdCgRoZpZALn64m+
# rpFu4Nj++Eir7gJS7JtLbiImXHTytuUMICHoIsQ4wCyjdzB1MA8GA1UdEwEB/wQF
# MAMBAf8wFAYDVR0RBA0wC4IJbG9jYWxob3N0MB0GA1UdJQQWMBQGCCsGAQUFBwMC
# BggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAqwwHQYDVR0OBBYEFD5Mlb74eGNr9OjR
# kRrd6PV8nCzlMAoGCCqGSM49BAMEA4GMADCBiAJCAWkQcWc4l8fuKD3Tc+fWhYlz
# ODcFmuQmFgUSVgTw8cdymHyRJYY6y9x8uCGCG1d/Ipn3aIRP3PPhqmU7jrLod6Dp
# AkIBEyydMP9xLC3klghq2ZPq4AKUf9kNdzMCJ6wIFFnVizrL5bWu82sQz1ZEhEE7
# EPITpvfo5IAYyiRXGBuHm51e0kU=
# -----END CERTIFICATE-----"
#
# export PLUGIN_SERVER_KEY="-----BEGIN EC PRIVATE KEY-----
# MIHcAgEBBEIAGnGm+1AvKonXhnd1mgFAfjsQjCgQf05/eHBtEKI02kbl2vLu8VHl
# NVlq//s3QGtwd5iWGXdhvXfu55Pi4kBkiuegBwYFK4EEACOhgYkDgYYABAEvlO14
# zMdz/l+0jqJ+IRYsQTmP2ADuotAi7IGoDwMOc6DAsqGsjwR9iH5CxTF/hyCXNfjE
# uxpdf2vISM8TF4jW1ACORQEI8YXiklBG1tidUWLrLQ55B9Kp0KBGhmlkAufrib6u
# kW7g2P74SKvuAlLsm0tuIiZcdPK25QwgIegixDjALA==
# -----END EC PRIVATE KEY-----"

# socat TCP-LISTEN:12345 UNIX-CONNECT:${(minus unix:)PLUGIN_SERVER_ENDPOINT}
# openssl s_client -connect localhost:12345 \
#   -cert <(echo "$PLUGIN_CLIENT_CERT") \
#   -key <(echo "$PLUGIN_CLIENT_KEY") \
#   -CAfile <(echo "$PLUGIN_SERVER_CERT") \
#   -servername localhost

# This is the endpoint and certificate that dev clients will use to test stuff.
# export PLUGIN_SERVER_ENDPOINT=unix:/var/folders/k6/jdp9qg890l553n47r3khszmc8t5ps6/T/plugin1058435072

# overwrite the static cert.
# export PLUGIN_SERVER_CERT="
# -----BEGIN CERTIFICATE-----
# MIICTzCCAbGgAwIBAgIRAMmz+xcI809Ngr3VZXsXnugwCgYIKoZIzj0EAwQwKDESMBAGA1UEChMJSGFzaGlDb3JwMRIwEAYDVQQDEwlsb2NhbGhvc3QwIBcNMjUwMTIzMDE0NTM3WhgPMjA1NTAxMjMxMzQ2MDdaMCgxEjAQBgNVBAoTCUhhc2hpQ29ycDESMBAGA1UEAxMJbG9jYWxob3N0MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBcM0gtm3FZUzyiWB2M3hX0lPmfy56aTROSmeqYbcO56T/mwYJqyERHztPyrrrK6Gi9/foNlz4UaqFY3D6il2bsCkB8wzjU5RtzLBr4mzy8nZgqz1C1jBuuehheDbCUVSVKIWtuin6k6eFVtQaYk5WKp2+YgMxTJKAsm7FogXF+w8yM9qjdzB1MA4GA1UdDwEB/wQEAwICrDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUDBjk2IMplCHTImqox9HWF26w7vswFAYDVR0RBA0wC4IJbG9jYWxob3N0MAoGCCqGSM49BAMEA4GLADCBhwJBMLLbbHKSzYKiO/CXCQg/uwieQ9G9ye5RvLDmnC5VgA7bZGwOF+Tpr0pDkNVOxEF2h22i8CbnKT7k60PD6XGDJNICQgFIyXNnQ615l2tM3/wHTos4Q36rcSt7S44sPhZfM/P5R71H/iiBqV/CUMhkKPuxoM7Vevl5jBdSKjOHIFwWpTyaPg==
# -----END CERTIFICATE-----
# "
