# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: e2e_greeting.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'e2e_greeting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x32\x65_greeting.proto\x12\x15\x65xamples.e2e_greeting\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rGreetingReply\x12\x0f\n\x07message\x18\x01 \x01(\t2b\n\x07Greeter\x12W\n\x05Greet\x12&.examples.e2e_greeting.GreetingRequest\x1a$.examples.e2e_greeting.GreetingReply\"\x00\x42\x45ZCgithub.com/provide-io/pyvider-rpcplugin/examples/proto/e2e_greetingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'e2e_greeting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/provide-io/pyvider-rpcplugin/examples/proto/e2e_greeting'
  _globals['_GREETINGREQUEST']._serialized_start=45
  _globals['_GREETINGREQUEST']._serialized_end=76
  _globals['_GREETINGREPLY']._serialized_start=78
  _globals['_GREETINGREPLY']._serialized_end=110
  _globals['_GREETER']._serialized_start=112
  _globals['_GREETER']._serialized_end=210
# @@protoc_insertion_point(module_scope)
