
# pyvider-rpcplugin/pyproject.toml

#? [tool.hatch.metadata]
[project]
name = "pyvider-rpcplugin"
version = "0.1.0"
description = "Pyvider RPC Plugin"
readme = "README.md"
authors = ["Tim Perkins <code@tim.life>"]

#? [tool.hatch.envs.default]
dependencies = [
    "attrs>=25.1.0",
    "cryptography>=44.0.1",
    "google>=3.0.0",
    "grpcio>=1.70.0",
    "hatch>=1.14.0",
    "protobuf>=5.29.3",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
]

################################################################################
# hatch
################################################################################

[tool.hatch.envs.test]
dependencies = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "ruff>=0.0.265",
]

# Tell Hatch where to find your package.
[tool.hatch.metadata.targets.wheel]
packages = [
    { include = "pyvider.rpcplugin", from = "src" }
]

[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"

################################################################################
# pytest
################################################################################

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

testpaths = ["tests"]
python_files = ["test_*.py"]

filterwarnings = [
    "ignore:cannot collect test class .* because it has a __init__ constructor:pytest.PytestCollectionWarning",
    "ignore:asyncio:selector_events.py:.* KqueueSelector
]

################################################################################

# [tool.ruff]
# line-length = 88
# target-version = ["py313"]
# exclude = ["build", "dist", ".venv"]
# select = ["E", "F", "I", "RUF", "C90"]
