# pyvider-rpcplugin/pyproject.toml

[project]
name = "pyvider-rpcplugin"
version = "0.1.0"
description = "Pyvider RPC Plugin"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Tim Perkins", email = "code@tim.life"}
]

dependencies = [
    "attrs>=25.1.0",
    "cryptography>=44.0.1",
    "google>=3.0.0",
    "grpcio>=1.70.0",
    "protobuf>=5.29.3",
]

[project.optional-dependencies]
dev = [
    "hatch>=1.14.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.0.265",
    "uv>=0.6.2",
    "hypothesis>=6.100.0",
    "bandit>=1.7.8",
]
telemetry = [
    "opentelemetry-exporter-otlp-proto-common>=1.30.0",
]

################################################################################
# hatch
################################################################################

[tool.hatch.envs.default]
dependencies = []

[tool.hatch.envs.test]
dependencies = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.0.265",
    "pyre-check>=0.9.19",
    "hypothesis>=6.100.0",
    "bandit>=1.7.8"
]

[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"
coverage = "pytest --cov=src --cov-report=term-missing"
lint = "ruff check src tests"
format = "ruff format src tests"
typecheck = "pyre check"
security = "bandit -r src"

[tool.hatch.envs.default.scripts]
run = "python -m pyvider.rpcplugin"

[tool.hatch.envs.docs]
dependencies = ["mkdocs", "mkdocs-material", "mkdocstrings[python]"]
scripts = {build = "mkdocs build", serve = "mkdocs serve"}

[tool.hatch.metadata.targets.wheel]
packages = [
    { include = "pyvider.rpcplugin", from = "src" }
]

################################################################################
# pytest
################################################################################

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

testpaths = ["tests"]
python_files = ["test_*.py"]

filterwarnings = [
    "ignore:cannot collect test class .* because it has a __init__ constructor:pytest.PytestCollectionWarning",
    #"ignore:.*Using selector: KqueueSelector.*",
    "ignore:.* KqueueSelector constructor:pytest.PytestCollectionWarning",
]

norecursedirs = [
    "build",
    "dist",
    "*.egg-info",
    ".venv",
    "**/*pb2*.py",
    "*/logger/messages/*",
]

################################################################################
# ruff
################################################################################

[tool.ruff]
select = ["E", "F", "I", "UP", "ANN", "B"]
ignore = [
    "ANN101",
    "ANN401",
    "B008",
    "E501",     # Line too long
]
exclude = ["tests/*", "**/*pb2*.py"]
line-length = 88

################################################################################
# coverage
################################################################################

[tool.coverage.run]
omit = [
    "tests/*",
    "logger/*",
    "crypto/debug.py"
]

################################################################################
# pyre
################################################################################

[tool.pyre]
source_directories = ["src"]
exclude = ["tests/*", "**/*pb2*.py"]
strict = true

[dependency-groups]
dev = [
    "bandit>=1.8.3",
    "hatch>=1.14.0",
    "hypothesis>=6.127.1",
    "mypy>=1.15.0",
    "pyre>=1.12.5",
    "pyre-check>=0.9.23",
    "pyre-extensions>=0.0.32",
    "pyright>=1.1.394",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.7",
    "tabulate>=0.9.0",
    "uv>=0.6.2",
]
