[pytest]
testpaths = tests
pythonpath = src
addopts = -v --tb=short
markers =
    slow: marks tests as slow running
    long_running: marks tests as long running
python_classes = Test* !TestRequest !TestResponse !TestStub