"""The server certificate has to vouch for the address it is served on.

The handshake line advertises the address the transport bound to -- by default
`127.0.0.1:<port>` -- and a TLS client dialling an address checks `iPAddress`
entries. A certificate carrying only `DNS:localhost` cannot be verified against
that literal address: the channel never becomes ready, and the client reports a
handshake timeout for a handshake that already succeeded.

The client also overrides the name it verifies, which is what go-plugin's own
host does. That keeps older servers working; this makes the certificate correct
on its own terms, so a client that does not override still connects.

SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import ipaddress

from cryptography import x509
import pytest

from pyvider.rpcplugin.server.network import _server_cert_alt_names


def test_loopback_ipv4_is_covered() -> None:
    """What the transport binds by default and the handshake advertises."""
    assert "127.0.0.1" in _server_cert_alt_names()


def test_loopback_ipv6_is_covered() -> None:
    assert "::1" in _server_cert_alt_names()


def test_localhost_is_still_covered() -> None:
    """go-plugin's host verifies against this name unconditionally."""
    assert "localhost" in _server_cert_alt_names()


def test_a_configured_host_is_added(monkeypatch: pytest.MonkeyPatch) -> None:
    """A server told to bind elsewhere presents a certificate for that address."""
    monkeypatch.setenv("PLUGIN_SERVER_HOST", "10.1.2.3")
    from pyvider.rpcplugin.config import rpcplugin_config

    monkeypatch.setattr(type(rpcplugin_config), "plugin_server_host", property(lambda self: "10.1.2.3"))
    assert "10.1.2.3" in _server_cert_alt_names()


def test_no_duplicates() -> None:
    names = _server_cert_alt_names()
    assert len(names) == len(set(names))


def test_the_generated_certificate_carries_an_ip_san() -> None:
    """End to end: the names reach the certificate as iPAddress entries."""
    from provide.foundation.crypto.certificates import Certificate

    cert = Certificate.create_self_signed_server_cert(
        common_name="pyvider.rpcplugin.autogen.server",
        organization_name="Pyvider AutoGenerated",
        validity_days=1,
        alt_names=_server_cert_alt_names(),
    )
    san = (
        x509.load_pem_x509_certificate(cert.cert_pem.encode())
        .extensions.get_extension_for_class(x509.SubjectAlternativeName)
        .value
    )
    assert ipaddress.ip_address("127.0.0.1") in san.get_values_for_type(x509.IPAddress)
    assert "localhost" in san.get_values_for_type(x509.DNSName)
