# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpctest.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpctest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpctest.proto\x12\x08grpctest\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0bTestRequest\x12\r\n\x05Input\x18\x01 \x01(\x05\"\x1e\n\x0cTestResponse\x12\x0e\n\x06Output\x18\x02 \x01(\x05\"Q\n\x0ePrintKVRequest\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\x15\n\x0bValueString\x18\x02 \x01(\tH\x00\x12\x12\n\x08ValueInt\x18\x03 \x01(\x05H\x00\x42\x07\n\x05Value\"\x11\n\x0fPrintKVResponse\"\"\n\x14\x42idirectionalRequest\x12\n\n\x02id\x18\x01 \x01(\r\"#\n\x15\x42idirectionalResponse\x12\n\n\x02id\x18\x01 \x01(\r\"3\n\x11PrintStdioRequest\x12\x0e\n\x06stdout\x18\x01 \x01(\x0c\x12\x0e\n\x06stderr\x18\x02 \x01(\x0c\"\r\n\x0bPingRequest\"\x1b\n\x0cPongResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xdb\x02\n\x04Test\x12\x39\n\x06\x44ouble\x12\x15.grpctest.TestRequest\x1a\x16.grpctest.TestResponse\"\x00\x12@\n\x07PrintKV\x12\x18.grpctest.PrintKVRequest\x1a\x19.grpctest.PrintKVResponse\"\x00\x12R\n\rBidirectional\x12\x1e.grpctest.BidirectionalRequest\x1a\x1f.grpctest.BidirectionalResponse\"\x00\x12=\n\x06Stream\x12\x15.grpctest.TestRequest\x1a\x16.grpctest.TestResponse\"\x00(\x01\x30\x01\x12\x43\n\nPrintStdio\x12\x1b.grpctest.PrintStdioRequest\x1a\x16.google.protobuf.Empty\"\x00\x32\x43\n\x08PingPong\x12\x37\n\x04Ping\x12\x15.grpctest.PingRequest\x1a\x16.grpctest.PongResponse\"\x00\x42\x0cZ\n./grpctestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpctest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./grpctest'
  _globals['_TESTREQUEST']._serialized_start=57
  _globals['_TESTREQUEST']._serialized_end=85
  _globals['_TESTRESPONSE']._serialized_start=87
  _globals['_TESTRESPONSE']._serialized_end=117
  _globals['_PRINTKVREQUEST']._serialized_start=119
  _globals['_PRINTKVREQUEST']._serialized_end=200
  _globals['_PRINTKVRESPONSE']._serialized_start=202
  _globals['_PRINTKVRESPONSE']._serialized_end=219
  _globals['_BIDIRECTIONALREQUEST']._serialized_start=221
  _globals['_BIDIRECTIONALREQUEST']._serialized_end=255
  _globals['_BIDIRECTIONALRESPONSE']._serialized_start=257
  _globals['_BIDIRECTIONALRESPONSE']._serialized_end=292
  _globals['_PRINTSTDIOREQUEST']._serialized_start=294
  _globals['_PRINTSTDIOREQUEST']._serialized_end=345
  _globals['_PINGREQUEST']._serialized_start=347
  _globals['_PINGREQUEST']._serialized_end=360
  _globals['_PONGRESPONSE']._serialized_start=362
  _globals['_PONGRESPONSE']._serialized_end=389
  _globals['_TEST']._serialized_start=392
  _globals['_TEST']._serialized_end=739
  _globals['_PINGPONG']._serialized_start=741
  _globals['_PINGPONG']._serialized_end=808
# @@protoc_insertion_point(module_scope)
