"""Prove the override against a real TLS handshake, not against an options dict.

The unit tests next door assert that `grpc.ssl_target_name_override` reaches the
channel options. They would pass just as happily if the value were wrong, which
is how a certificate that vouches for `localhost` came to be verified against a
literal `127.0.0.1` for as long as it was.

These stand up an actual gRPC server with the certificate the plugin server
generates -- `DNS:localhost`, no IP SAN -- bind it to 127.0.0.1, and ask whether
the channel reaches ready. Without the override it cannot: verification fails,
the channel stays not-ready, and the client burns its budget on retries before
reporting a HandshakeError for a handshake that already succeeded.

Windows was where this surfaced, because its default transport list is TCP-only
while every other platform prefers a unix socket. Nothing here is Windows-
specific, so the regression is caught wherever the suite runs.

SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator

import grpc
import pytest
import pytest_asyncio
from provide.foundation.crypto.certificates import Certificate

#: Long enough for a local TLS handshake, short enough that the negative case
#: does not dominate the suite. A successful loopback channel is ready in ~10ms.
READY_TIMEOUT_S = 3.0

KEEPALIVE_OPTIONS: list[tuple[str, int | bool | str]] = [
    ("grpc.keepalive_time_ms", 30000),
]


@pytest.fixture(scope="module")
def server_certificate() -> Certificate:
    """The certificate the plugin server auto-generates: localhost, no IP SAN."""
    return Certificate.create_self_signed_server_cert(
        common_name="pyvider.rpcplugin.autogen.server",
        organization_name="Pyvider AutoGenerated",
        validity_days=1,
        alt_names=["localhost"],
    )


@pytest_asyncio.fixture
async def tcp_endpoint(server_certificate: Certificate) -> AsyncIterator[str]:
    """A TLS gRPC server on loopback, addressed the way the handshake line is."""
    server = grpc.aio.server()
    credentials = grpc.ssl_server_credentials(
        [(server_certificate.key_pem.encode(), server_certificate.cert_pem.encode())]
    )
    port = server.add_secure_port("127.0.0.1:0", credentials)
    await server.start()
    try:
        yield f"127.0.0.1:{port}"
    finally:
        await server.stop(grace=None)


async def _channel_becomes_ready(
    endpoint: str, certificate: Certificate, options: list[tuple[str, int | bool | str]]
) -> bool:
    credentials = grpc.ssl_channel_credentials(root_certificates=certificate.cert_pem.encode())
    async with grpc.aio.secure_channel(endpoint, credentials, options=options) as channel:
        try:
            await asyncio.wait_for(channel.channel_ready(), timeout=READY_TIMEOUT_S)
        except (TimeoutError, asyncio.TimeoutError):
            return False
        return True


async def test_without_the_override_the_channel_never_becomes_ready(
    tcp_endpoint: str, server_certificate: Certificate
) -> None:
    """The defect: an IP literal matches no DNS SAN, so verification fails."""
    assert not await _channel_becomes_ready(tcp_endpoint, server_certificate, KEEPALIVE_OPTIONS)


async def test_with_the_override_the_channel_becomes_ready(
    tcp_endpoint: str, server_certificate: Certificate
) -> None:
    """The fix, exercised end to end against a real TLS handshake."""
    options = [*KEEPALIVE_OPTIONS, ("grpc.ssl_target_name_override", "localhost")]
    assert await _channel_becomes_ready(tcp_endpoint, server_certificate, options)


async def test_the_client_asks_for_that_override_on_tcp(
    tcp_endpoint: str, server_certificate: Certificate
) -> None:
    """The options the client actually builds are the ones that work above.

    Ties the unit-level assertion to the behavioural one, so neither can drift
    into passing on its own.
    """
    from pyvider.rpcplugin.client.process import ClientProcessMixin

    class _Client(ClientProcessMixin):
        def __init__(self) -> None:
            self._transport_name = "tcp"
            self._server_cert = "CERTDATA"
            self.logger = type("_L", (), {"debug": lambda *a, **k: None})()

    options = _Client()._get_channel_options()  # type: ignore[arg-type]
    assert await _channel_becomes_ready(tcp_endpoint, server_certificate, options)
