#
# pyvider/rpcplugin/server/network.py
#
"""
Network setup, handshake, and credential handling for RPC plugin servers.

This module contains the ServerNetworkMixin with methods for handling
transport setup, TLS/mTLS credentials, handshake negotiation, and
server configuration.
"""

import asyncio
from pathlib import Path
import sys
from typing import Any, cast

import grpc
from grpc.aio import server as GRPCServer
from grpc_health.v1 import health_pb2_grpc
from provide.foundation import logger
from provide.foundation.crypto import Certificate

from pyvider.rpcplugin.config import rpcplugin_config
from pyvider.rpcplugin.exception import (
    ProtocolError,
    SecurityError,
    TransportError,
)
from pyvider.rpcplugin.handshake import (
    build_handshake_response,
    negotiate_protocol_version,
    negotiate_transport,
    validate_magic_cookie,
)
from pyvider.rpcplugin.protocol import register_protocol_service
from pyvider.rpcplugin.transport import TCPSocketTransport, UnixSocketTransport
from pyvider.rpcplugin.transport.types import (
    RPCPluginTransport as RPCPluginTransportType,
)


# Network and transport-related methods that will be mixed into RPCPluginServer
class ServerNetworkMixin:
    """Mixin class containing network and transport methods for RPCPluginServer."""

    # Forward declarations for attributes that will be on the main server class
    config: dict[str, Any] | None
    protocol: Any  # BaseRpcAbcProtocol
    handler: Any  # HandlerT
    transport: Any | None  # TransportT
    _transport: Any | None  # TransportT
    _server: Any | None  # ServerT
    _handshake_config: Any  # HandshakeConfig
    _protocol_version: int
    _transport_name: str
    _server_cert_obj: Certificate | None
    _port: int | None
    _serving_future: asyncio.Future[None]
    _serving_event: asyncio.Event
    _shutdown_event: asyncio.Event
    _rate_limiter: Any | None  # TokenBucketRateLimiter
    _health_servicer: Any | None  # HealthServicer

    # Forward declarations for methods from main class
    def _get_instance_override(self, key: str, default_value: Any) -> Any: ...

    def _read_client_cert(self) -> str | None:
        """Read client certificate configuration if available."""
        return self._get_instance_override("PLUGIN_CLIENT_CERT", rpcplugin_config.plugin_client_cert)

    def _generate_server_credentials(self) -> grpc.ServerCredentials | None:
        """
        Generate gRPC server credentials based on configuration.

        This method handles both manual certificate configuration and
        automatic mTLS certificate generation. It supports client certificate
        validation when configured.

        Returns:
            gRPC server credentials for secure connections, or None for insecure mode

        Raises:
            SecurityError: If certificate configuration or generation fails
        """
        server_cert_conf = self._get_instance_override(
            "PLUGIN_SERVER_CERT", rpcplugin_config.plugin_server_cert
        )
        server_key_conf = self._get_instance_override("PLUGIN_SERVER_KEY", rpcplugin_config.plugin_server_key)
        auto_mtls = self._get_instance_override("PLUGIN_AUTO_MTLS", rpcplugin_config.plugin_auto_mtls)
        client_root_certs_conf = self._get_instance_override(
            "PLUGIN_CLIENT_ROOT_CERTS", rpcplugin_config.plugin_client_root_certs
        )

        if not auto_mtls and not (server_cert_conf and server_key_conf):
            logger.info("auto_mtls is false and no server cert/key provided. Operating insecurely.")
            return None

        if server_cert_conf and server_key_conf:
            try:
                self._server_cert_obj = Certificate(
                    cert_pem_or_uri=server_cert_conf, key_pem_or_uri=server_key_conf
                )
            except Exception as e:
                raise SecurityError(f"Failed to load server certificate/key: {e}") from e
        elif auto_mtls:
            try:
                self._server_cert_obj = Certificate.create_self_signed_server_cert(
                    common_name="pyvider.rpcplugin.autogen.server",
                    organization_name="Pyvider AutoGenerated",
                    validity_days=365,
                    alt_names=["localhost"],
                )
                common_name_val = getattr(self._server_cert_obj, "common_name", "Unknown")
                logger.info(f"📜🔑🏭 Created new self-signed SERVER certificate for CN={common_name_val}")
            except Exception as e:
                raise SecurityError(f"Failed to auto-generate server certificate: {e}") from e
        else:
            logger.warning("No server cert/key configured and auto_mtls is false. Proceeding insecurely.")
            return None

        if not (self._server_cert_obj and self._server_cert_obj.cert and self._server_cert_obj.key):
            raise SecurityError("Server certificate object is invalid or missing PEM data after processing.")

        key_bytes = self._server_cert_obj.key.encode("utf-8")
        cert_bytes = self._server_cert_obj.cert.encode("utf-8")
        client_ca_pem_bytes = None
        require_auth = False

        if auto_mtls and client_root_certs_conf:
            require_auth = True
            try:
                if isinstance(client_root_certs_conf, str) and client_root_certs_conf.startswith("file://"):
                    with Path(client_root_certs_conf[7:]).open("rb") as f:
                        client_ca_pem_bytes = f.read()
                elif isinstance(client_root_certs_conf, str):
                    client_ca_pem_bytes = client_root_certs_conf.encode("utf-8")
            except Exception as e:
                raise SecurityError(f"Failed to load client root CAs: {e}") from e
        elif auto_mtls:
            logger.warning(
                "auto_mtls is True, but PLUGIN_CLIENT_ROOT_CERTS not provided. "
                "Client certs will not be required/verified."
            )
            require_auth = False

        return grpc.ssl_server_credentials(
            private_key_certificate_chain_pairs=[(key_bytes, cert_bytes)],
            root_certificates=client_ca_pem_bytes,
            require_client_auth=require_auth,
        )

    async def _setup_server(self) -> None:
        """
        Set up the gRPC server with transport, credentials, and service registration.

        This method handles the complete server setup process including:
        - Creating the gRPC server with interceptors
        - Registering protocol services
        - Setting up TLS/mTLS credentials
        - Configuring transport binding
        - Starting the server

        Raises:
            TransportError: If transport or server setup fails
            SecurityError: If credential setup fails
            ProtocolError: If service registration fails
        """
        try:
            # Import RateLimitingInterceptor from core module
            from .core import RateLimitingInterceptor

            interceptors_list: list[grpc.aio.ServerInterceptor] = (
                [RateLimitingInterceptor(self._rate_limiter)] if self._rate_limiter else []
            )
            self._server = cast(
                Any,  # ServerT
                GRPCServer(interceptors=interceptors_list),
            )

            proto_instance = self.protocol
            await proto_instance.add_to_server(handler=self.handler, server=self._server)

            if self._server is None:
                raise TransportError("Server object not initialized before registration.")

            concrete_server = cast(grpc.aio.Server, self._server)
            register_protocol_service(server=concrete_server, shutdown_event=self._shutdown_event)
            if self._health_servicer and self._server:
                health_pb2_grpc.add_HealthServicer_to_server(self._health_servicer, concrete_server)

            creds = self._generate_server_credentials()

            if self._transport is None:
                raise TransportError("Transport not initialized before server setup.")

            active_transport_checked = cast(RPCPluginTransportType, self._transport)
            await active_transport_checked.listen()
            endpoint = active_transport_checked.endpoint
            if not endpoint:
                raise TransportError("Transport endpoint not available after listen.")

            bind_address = (
                f"unix:{endpoint}" if isinstance(active_transport_checked, UnixSocketTransport) else endpoint
            )

            server_for_port = cast(grpc.aio.Server, self._server)
            port_num = 0
            if creds:
                port_num = server_for_port.add_secure_port(bind_address, creds)
                logger.info(f"🔒 Server starting in secure mode on {bind_address} (port_num: {port_num})")
            else:
                port_num = server_for_port.add_insecure_port(bind_address)
                logger.info(f"🔌 Server starting in insecure mode on {bind_address} (port_num: {port_num})")

            if isinstance(active_transport_checked, TCPSocketTransport):
                # Determine if a specific port was requested initially,
                # either via injected transport or via PLUGIN_SERVER_ENDPOINT
                # configuration.
                initial_requested_port_val = 0  # Default to ephemeral

                # Check if self.transport (the one RPCPluginServer was
                # initialized with, if any) had a specific port.
                # self.transport is the transport instance passed to
                # RPCPluginServer's constructor.
                # active_transport_checked is self._transport, which might be
                # from self.transport or negotiated.
                # In the failing test, self.transport is set, and is the same as
                # active_transport_checked.
                original_transport_config_port = -1  # Sentinel for not configured via direct transport
                if (
                    self.transport is not None
                    and hasattr(self.transport, "port")
                    and isinstance(self.transport, TCPSocketTransport)
                ):
                    # Check the port value of the transport instance provided
                    # at server construction
                    original_transport_config_port = self.transport.port

                if original_transport_config_port != -1 and original_transport_config_port != 0:
                    # A specific port was provided via the transport object itself
                    initial_requested_port_val = original_transport_config_port
                else:
                    # No specific port on direct transport, or no direct
                    # transport, check config
                    port_conf = self._get_instance_override(
                        "PLUGIN_SERVER_PORT", rpcplugin_config.plugin_server_port
                    )
                    if port_conf is not None:
                        try:
                            initial_requested_port_val = int(port_conf)
                        except (ValueError, TypeError):
                            logger.warning(
                                "Could not parse port from "
                                f"PLUGIN_SERVER_PORT='{port_conf}'. "
                                "Assuming ephemeral."
                            )
                            initial_requested_port_val = 0  # Fallback to ephemeral if parse fails
                    else:
                        # No PLUGIN_SERVER_PORT set, assume ephemeral
                        initial_requested_port_val = 0

                is_specific_port_requested = initial_requested_port_val != 0

                # port_num is the result from
                # grpc_server.add_insecure_port(bind_address)
                if port_num == 0 and is_specific_port_requested:
                    raise TransportError(
                        "Failed to bind to specifically requested TCP port in "
                        f"{bind_address} (requested port was "
                        f"{initial_requested_port_val}). Port returned by gRPC was 0."
                    )

                self._port = port_num  # Store the actual bound port
                active_transport_checked.port = port_num  # Update transport's port with actual

                current_host = active_transport_checked.host if active_transport_checked.host else "0.0.0.0"
                active_transport_checked.endpoint = f"{current_host}:{port_num}"

            server_to_start = cast(grpc.aio.Server, self._server)
            await server_to_start.start()
        except (TransportError, ProtocolError, SecurityError):
            raise
        except Exception as e:
            raise TransportError(f"gRPC server failed to start: {e}") from e

    async def _negotiate_handshake(self) -> None:
        """
        Perform handshake protocol negotiation with the client.

        This method validates the magic cookie, negotiates protocol version,
        and sets up transport if not already configured.

        Raises:
            ProtocolError: If handshake negotiation fails
            TransportError: If transport setup fails
        """
        validate_magic_cookie(
            magic_cookie_key=self._handshake_config.magic_cookie_key,
            magic_cookie_value=self._handshake_config.magic_cookie_value,
        )
        self._protocol_version = negotiate_protocol_version(self._handshake_config.protocol_versions)
        if not self._transport:
            negotiated_transport_typed: RPCPluginTransportType
            (
                self._transport_name,
                negotiated_transport_typed,
            ) = await negotiate_transport(self._handshake_config.supported_transports)
            self._transport = cast(Any, negotiated_transport_typed)  # TransportT
        else:
            self._transport_name = "tcp" if isinstance(self._transport, TCPSocketTransport) else "unix"

    async def _build_and_send_handshake_response(self) -> None:
        """
        Build and send handshake response to stdout.

        This method creates the handshake response with transport and certificate
        information and sends it to stdout for the client to read.

        Raises:
            TransportError: If transport is not properly initialized
        """
        if self._transport is None:
            err_msg = "Internal error: Transport is None before building handshake response."
            logger.error(f"💣💥 {err_msg}")
            raise TransportError(err_msg)

        concrete_transport = cast(RPCPluginTransportType, self._transport)
        response = await build_handshake_response(
            plugin_version=self._protocol_version,
            transport_name=self._transport_name,
            transport=concrete_transport,
            server_cert=self._server_cert_obj,
            port=self._port,
        )
        sys.stdout.buffer.write(f"{response}\n".encode())
        sys.stdout.buffer.flush()
