# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import configstore.proto.configstore_pb2 as configstore__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in configstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigStoreStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/configstore.ConfigStore/Get',
                request_serializer=configstore__pb2.GetRequest.SerializeToString,
                response_deserializer=configstore__pb2.ConfigEntry.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/configstore.ConfigStore/Set',
                request_serializer=configstore__pb2.SetRequest.SerializeToString,
                response_deserializer=configstore__pb2.Empty.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/configstore.ConfigStore/Delete',
                request_serializer=configstore__pb2.DeleteRequest.SerializeToString,
                response_deserializer=configstore__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchGet = channel.unary_unary(
                '/configstore.ConfigStore/BatchGet',
                request_serializer=configstore__pb2.BatchGetRequest.SerializeToString,
                response_deserializer=configstore__pb2.BatchGetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/configstore.ConfigStore/List',
                request_serializer=configstore__pb2.ListRequest.SerializeToString,
                response_deserializer=configstore__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/configstore.ConfigStore/Watch',
                request_serializer=configstore__pb2.WatchRequest.SerializeToString,
                response_deserializer=configstore__pb2.ConfigEntry.FromString,
                _registered_method=True)


class ConfigStoreServicer(object):
    """Service definition
    """

    def Get(self, request, context):
        """Single key operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGet(self, request, context):
        """Batch operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Query operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Watch for changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=configstore__pb2.GetRequest.FromString,
                    response_serializer=configstore__pb2.ConfigEntry.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=configstore__pb2.SetRequest.FromString,
                    response_serializer=configstore__pb2.Empty.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=configstore__pb2.DeleteRequest.FromString,
                    response_serializer=configstore__pb2.Empty.SerializeToString,
            ),
            'BatchGet': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGet,
                    request_deserializer=configstore__pb2.BatchGetRequest.FromString,
                    response_serializer=configstore__pb2.BatchGetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=configstore__pb2.ListRequest.FromString,
                    response_serializer=configstore__pb2.ListResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=configstore__pb2.WatchRequest.FromString,
                    response_serializer=configstore__pb2.ConfigEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'configstore.ConfigStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('configstore.ConfigStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigStore(object):
    """Service definition
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/configstore.ConfigStore/Get',
            configstore__pb2.GetRequest.SerializeToString,
            configstore__pb2.ConfigEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/configstore.ConfigStore/Set',
            configstore__pb2.SetRequest.SerializeToString,
            configstore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/configstore.ConfigStore/Delete',
            configstore__pb2.DeleteRequest.SerializeToString,
            configstore__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/configstore.ConfigStore/BatchGet',
            configstore__pb2.BatchGetRequest.SerializeToString,
            configstore__pb2.BatchGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/configstore.ConfigStore/List',
            configstore__pb2.ListRequest.SerializeToString,
            configstore__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/configstore.ConfigStore/Watch',
            configstore__pb2.WatchRequest.SerializeToString,
            configstore__pb2.ConfigEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
