# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"?\n\x0b\x43hatMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"3\n\x12SendMessageRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x17\n\x15MessageHistoryRequest\"=\n\x16MessageHistoryResponse\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.chat.ChatMessage2\xd9\x01\n\x0b\x43hatService\x12\x42\n\x0bSendMessage\x12\x18.chat.SendMessageRequest\x1a\x19.chat.SendMessageResponse\x12N\n\x11GetMessageHistory\x12\x1b.chat.MessageHistoryRequest\x1a\x1c.chat.MessageHistoryResponse\x12\x36\n\nChatStream\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x42=Z;github.com/provide-io/pyvider-rpcplugin/examples/chat/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/provide-io/pyvider-rpcplugin/examples/chat/proto'
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=83
  _globals['_SENDMESSAGEREQUEST']._serialized_start=85
  _globals['_SENDMESSAGEREQUEST']._serialized_end=136
  _globals['_SENDMESSAGERESPONSE']._serialized_start=138
  _globals['_SENDMESSAGERESPONSE']._serialized_end=199
  _globals['_EMPTY']._serialized_start=201
  _globals['_EMPTY']._serialized_end=208
  _globals['_MESSAGEHISTORYREQUEST']._serialized_start=210
  _globals['_MESSAGEHISTORYREQUEST']._serialized_end=233
  _globals['_MESSAGEHISTORYRESPONSE']._serialized_start=235
  _globals['_MESSAGEHISTORYRESPONSE']._serialized_end=296
  _globals['_CHATSERVICE']._serialized_start=299
  _globals['_CHATSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
